name: CI
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Debug API call
        run: |
          curl -H "Authorization: token ${{ steps.app-token.outputs.token }}" \
          -H "Content-Type: application/json" \
          https://api.github.com/user

      - run: npm install --frozen-lockfile
      - run: npm run lint && npm run build
