name: CI
on:
  push:
    branches:
      - '**'

jobs:
  build:
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App installation token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Debug API call
        run: |
          curl -H "Authorization: token ${{ steps.generate_token.outputs.token }}" \
          -H "Content-Type: application/json" \
          https://api.github.com/user

      - run: npm install --frozen-lockfile
      - run: npm run lint && npm run build
